Repository AY2223S2-CS2103T-F12-3/tp, pull requests merged in 2023-03, with the labels that each got.

#101 Changes to Person list
  src/main/java/seedu/address/ui/body/address/PersonCard.java
  src/main/java/seedu/address/ui/body/address/PersonListDivider.java
  src/main/java/seedu/address/ui/body/address/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/body/address/PersonListCard.fxml
  src/main/resources/view/body/address/PersonListDivider.fxml
  src/main/resources/view/body/address/PersonListPanel.fxml
Labels: priority.Medium

#104 Fixes duplicated tags issue
  src/main/java/seedu/address/ui/body/address/PersonCard.java
Labels: priority.High

#115 Revamp person list rendering
  src/main/java/seedu/address/ui/body/address/PersonCard.java
  src/main/java/seedu/address/ui/body/address/PersonListDivider.java
  src/main/java/seedu/address/ui/body/address/PersonListPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/body/address/PersonListCard.fxml
Labels: priority.Medium

#129 Light and dark modes!
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/body/BodyPanel.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: priority.Medium, type.Enhancement

#131 New calendar view for events
  build.gradle
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/event/fields/DateTime.java
  src/main/java/seedu/address/model/user/User.java
  src/main/java/seedu/address/storage/user/JsonAdaptedEvent.java
  src/main/java/seedu/address/ui/body/BodyPanel.java
  src/main/java/seedu/address/ui/body/calendar/CalendarDayCard.java
  src/main/java/seedu/address/ui/body/calendar/CalendarEventCard.java
  src/main/java/seedu/address/ui/body/calendar/CalendarPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/body/calendar/CalendarDayCard.fxml
  src/main/resources/view/body/calendar/CalendarDayView.fxml
  src/main/resources/view/body/calendar/CalendarEventCard.fxml
  src/main/resources/view/body/calendar/CalendarPanel.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/event/fields/DateTimeTest.java
Labels: priority.High, type.Enhancement

#137 Update build.gradle for assertions
  build.gradle
Labels: priority.High, type.Task

#134 Changes to event DateTime handling
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/logic/ui/tab/TabType.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/RecurringEvent.java
  src/main/java/seedu/address/model/event/fields/DateTime.java
  src/main/java/seedu/address/model/event/fields/Recurrence.java
  src/main/java/seedu/address/ui/body/BodyPanel.java
  src/main/java/seedu/address/ui/body/calendar/CalendarEventCard.java
  src/main/java/seedu/address/ui/body/calendar/CalendarPanel.java
  src/main/resources/view/DarkTheme.css
  src/test/java/seedu/address/logic/ui/tab/TabUtilTest.java
  src/test/java/seedu/address/model/event/fields/DateTimeTest.java
Labels: priority.Medium, type.Enhancement

#151 Update DG Guide for Storage, Model and added a new Person UML diagram.
  docs/DeveloperGuide.md
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/PersonDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/PersonDiagram.png
  docs/images/StorageClassDiagram.png
  docs/team/igezt.md
  src/main/java/seedu/address/logic/commands/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/EditUserCommand.java
  src/main/java/seedu/address/logic/parser/editpersoncommandsparser/EditContactCommandParser.java
  src/main/java/seedu/address/logic/parser/editpersoncommandsparser/EditPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/editpersoncommandsparser/EditUserCommandParser.java
  src/main/java/seedu/address/logic/parser/editpersoncommandsparser/PersonDescriptor.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditContactCommandTest.java
  src/test/java/seedu/address/logic/commands/PersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditContactCommandParserTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: deadline.Strict

#161 Add support for users to tag Person to Events.
  src/main/java/seedu/address/logic/commands/AddEventCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/event/Event.java
  src/main/java/seedu/address/model/event/UniqueEventList.java
  src/main/java/seedu/address/model/event/fields/Description.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/user/User.java
  src/main/java/seedu/address/model/user/UserData.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.Critical

#171 Add model support for DeleteEventCommand.
  src/main/java/seedu/address/logic/commands/DeleteEventCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/user/User.java
  src/main/java/seedu/address/model/user/UserData.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: deadline.Strict

#174 Update landing page and my PPP
  docs/images/Ui.png
  docs/index.md
  docs/team/hansstanley.md
Labels: type.Documentation

#176 NeoBook replacements
  docs/_config.yml
  docs/images/Ui.png
Labels: type.Documentation

#183 Clean up traces of AB-3
  README.md
  build.gradle
  docs/AboutUs.md
  docs/DevOps.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/team/Shuggan.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/person/fields/enums/Genders.java
Labels: type.Documentation

#192 Build module list into NeoBook
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/fields/Modules.java
  src/main/java/seedu/address/model/person/fields/subfields/NusMod.java
  src/main/java/seedu/address/storage/addressbook/JsonAdaptedNusMod.java
  src/main/resources/data/modules.json
Labels: deadline.Strict
